branches:
  - "10.0"
  - "11.0"
  - "12.0"
  - "13.0"

repos:
  it-projects-llc/misc-addons:
  it-projects-llc/pos-addons:
  it-projects-llc/website-addons:
  it-projects-llc/mail-addons:
  it-projects-llc/access-addons:
