name: "ITPP Runbot: Install"

on:
  push:
    paths:
      - ".github/workflows/itpp-runbot-install.yml"  # run the workflow on uploading or updating
      - ".itpp-runbot/config.yml"  # update itpp-runbot.yml on changing settings

jobs:
  upload-files:

    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v2-beta
      with:
        path: repo
    - name: Get Runbot Version
      run: |
        ITPP_RUNBOT_VERSION="$(cat repo/config.yaml | grep itpp-runbot-version | awk '{print $NF}')"
        # use master by default
        ITPP_RUNBOT_VERSION="${ITPP_RUNBOT_VERSION:-master}"
        # see https://help.github.com/en/actions/automating-your-workflow-with-github-actions/development-tools-for-github-actions
        echo "::set-env name=ITPP_RUNBOT_VERSION::$ITPP_RUNBOT_VERSION"
    - name: Checkout ITPP-Runbot
      uses: actions/checkout@v2-beta
      with:
        repository: it-projects-llc/itpp-runbot
        path: itpp-runbot
        ref: ${{ env.ITPP_RUNBOT_VERSION }}
    - name: Check for initial upload editable files
      run: |
        echo "ls" && ls
        echo "ls itpp-runbot" && ls itpp-runbot
        echo "ls repo" && ls repo
        cp -rnT itpp-runbot/editable-files/ repo/
    - name: Update Docker Workflow
      run: |
        SCHEDULE_CRON="$(cat repo/.itpp-runbot/config.yaml | grep image-rebuilding-schedule | awk -F\" '{print $2}')"
        cp itpp-runbot/workflows/itpp-runbot.yml repo/.github/workflows/
        sed -i "s/SCHEDULE_CRON/$SCHEDULE_CRON/" repo/.github/workflows/itpp-runbot.yml
    - run: |
        # TODO: move this to the commit action
        echo ${GITHUB_REF}
        BRANCH="${GITHUB_REF:11}"
        echo "::set-env name=BRANCH::$BRANCH"
    - name: Commit changes
      uses: yelizariev/git-auto-commit-action@custom-repo-path
      with:
        #author_name: Marc Demo (Github Actions)
        #author_email: i18n-bot@it-projects.info
        branch: ${{ env.BRANCH }}
        commit_message: | 
          :alien: Update ITPP Runbot files

          > Sent from Github Actions (see .github/workflows/itpp-runbot-install.yml)
        repository: repo
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Notify Github App
      run: |
        [[ "$NOTIFY_APP" = "yes" ]] && echo "TODO curl request" || true
