version: "2.4"

services:
    odoo:
        image: $REGISTRY/$REPOSITORY/dinar-odoo-$REPO_NAME:$VERSION
        hostname: "$SMTP_REAL_NON_CANONICAL_DEFAULT" # TODO
        tty: true
        ports:
            - "127.0.0.1:6899:6899"
            - "127.0.0.1:8069:8069"
        environment:
            DOODBA_ENVIRONMENT: "${DOODBA_ENVIRONMENT-devel}"
            LIST_DB: "true"
            PTVSD_ENABLE: "${DOODBA_PTVSD_ENABLE:-0}"
            PGDATABASE: &dbname DINAR
            PYTHONOPTIMIZE: ""
            PYTHONPATH: /opt/odoo/custom/src/odoo
            SMTP_PORT: "1025"
            # To avoid installing demo data export DOODBA_WITHOUT_DEMO=all
            WITHOUT_DEMO: "${DOODBA_WITHOUT_DEMO-false}"
            EMAIL_FROM: "$SMTP_DEFAULT_FROM"
            PGUSER: &dbuser "odoo"
            DB_FILTER: ".*"
            PROXY_MODE: "$ODOO_PROXY_MODE"
        volumes:
            - ./pr-files:/opt/odoo/custom/src/private/

        depends_on:
            - db
            - smtp
            - wdb
        command:
            - odoo
            - --limit-memory-soft=0
            - --limit-time-real-cron=9999999
            - --limit-time-real=9999999
            - --workers=0
            - --init=$MODULES
            #- --dev=reload,qweb,werkzeug,xml

    db:
        image: $REGISTRY/$REPOSITORY/dinar-db-$REPO_NAME:$VERSION
        shm_size: 512mb
        environment:
            POSTGRES_DB: *dbname
            POSTGRES_USER: *dbuser
            POSTGRES_PASSWORD: odoopassword
            CONF_EXTRA: |
                work_mem = 32MB

    smtp:
        image: mailhog/mailhog
        ports:
            - "127.0.0.1:8025:8025"

    wdb:
        image: kozea/wdb
        ports:
            - "127.0.0.1:1984:1984"
        # HACK https://github.com/Kozea/wdb/issues/136
        stop_signal: KILL
